excluded:
  - .build
  - "**/.build"
  - FifteenTwo.xcodeproj

identifier_name:
  excluded:
    - i
    - j
    - n
    - id
    - z
    - lo
    - hi
    - go
    - k

function_parameter_count:
  warning: 7
  error: 9
